INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('B101','AMS','BOM','12:00','19:30',750) 
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('C101','AMS','BLR','13:00','18:30',800) 
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('D101','AMS','MAA','09:00','15:00',600) 
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('E101','MAA','BOM','16:00','17:30',100) 
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('F101','BOM','DEL','20:30','21:30',80)
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('G101','BOM','DEL','18:00','19:30',100) 
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('A201','LHR','DEL','11:30','17:00',600) 
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('B201','LHR','BOM','12:35','19:30',750) 
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('C201','LHR','BLR','13:45','18:30',800) 
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('D201','LHR','MAA','09:00','15:00',600) 
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('E201','DEL','BOM','18:45','20:15',100) 
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('F201','BOM','DEL','21:15','22:30',80)
INSERT INTO flight_details (flight_number,origin,destination,departure_time,arrival_time,price) VALUES ('G01','BOM','DEL','20:20','21:30',100) 

